// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB3wj20SS7Z-vMuS7abYiooHjz37TwTto',
    appId: '1:821504378051:android:0a19240be4d1cf04b10e76',
    messagingSenderId: '821504378051',
    projectId: 'insideaerotech',
    storageBucket: 'insideaerotech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4-MQ0agGyrj-Jr9SD3MuA0Bxfj2HMVE',
    appId: '1:821504378051:ios:f306a785492b7650b10e76',
    messagingSenderId: '821504378051',
    projectId: 'insideaerotech',
    storageBucket: 'insideaerotech.appspot.com',
    androidClientId: '821504378051-1vnm3mnp959vfa7l2e3h6jqct2iosght.apps.googleusercontent.com',
    iosClientId: '821504378051-48bjeqtj3u5vfgogebimk2i5bna75plr.apps.googleusercontent.com',
    iosBundleId: 'com.example.insideflyingconcept',
  );

}